name: To Epitech Github

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  to_epitech:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Epitech Github
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPITECH_URL }}
          ssh_private_key:
            ${{ secrets.SSH_TO_EPITECH }}
